sudo: required

services:
  - docker

language: generic

install:
  - cd CodeChill-IDE
  - IMAGE="codechillaluna/code-chill-ide"
  - travis_wait docker build -f DockerFile -t $IMAGE . --no-cache

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "$IMAGE"
  on:
    branch: master

notifications:
  email: false