FROM ubuntu

RUN apt-get update \
&& apt-get upgrade -y \
&& apt-get install -y sudo vim nano htop python3 python3-pip build-essential man locales locales-all

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8